chore: check package matches tag

diff --git a/.github/workflows/continuous-integration-and-deployment.yml b/.github/workflows/continuous-integration-and-deployment.yml
--- a/.github/workflows/continuous-integration-and-deployment.yml
+++ b/.github/workflows/continuous-integration-and-deployment.yml
@@ -40,6 +40,19 @@ jobs:
           string: ${{ github.ref_name }}
           replace-with: $1
 
+      - name: Extract version from package
+        id: extract-version-from-package
+        uses: sergeysova/jq-action@v2
+        with:
+          cmd: jq .version package.json -r
+
+      - name: Verify version match
+        if: ${{ steps.get-version-from-tag.outputs.replaced != steps.extract-version-from-package.outputs.value }}
+        run: |
+          echo "::error::Version in the package.json and tag don't match"
+          exit 1
+        shell: bash
+
       - name: Create release
         uses: ncipollo/release-action@v1.12.0
         with:
